version: '3'

networks:
  mongodb_net:

services:

  mongodb-primary:
    image: 'bitnami/mongodb:latest'
    environment:
      - MONGODB_REPLICA_SET_NAME=my-replica-set  # Set your replica set name here
      - MONGODB_ADVERTISED_HOSTNAME=localhost
      - MONGODB_REPLICA_SET_MODE=primary
      - ALLOW_EMPTY_PASSWORD=yes
    ports:
      - 27017:27017
    volumes:
      - ./docker-data/mongodb_primary_data:/bitnami
    networks:
      - mongodb_net

  mongodb-secondary:
    image: 'bitnami/mongodb:latest'
    environment:
      - MONGODB_REPLICA_SET_NAME=my-replica-set  # Set your replica set name here
      - MONGODB_REPLICA_SET_MODE=secondary
      - MONGODB_INITIAL_PRIMARY_HOST=mongodb-primary
    volumes:
      - ./docker-data/mongodb_secondary_data:/bitnami
    networks:
      - mongodb_net

  maildev:
    image: maildev/maildev:latest
    ports:
      - 1080:1080
      - 1025:1025
      - 587:587
    volumes:
      - ./docker-data/maildev_data:/maildev
    restart: always
