version: '3.8'

services:
  mongodb:
    image: mongo:latest
    restart: always
    container_name: contacthub-mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGODB_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGODB_PASSWORD}

volumes:
  mongodb_data: